### ISSUE TITLE
Some importer bugs/improvements

### ISSUE THREAD

**Issue by labor4** [kevinpapst/kimai2#553]
V0.7 stable, Importer from v1:
- If a userID of timesheet entry points to a user that is not in the (v1) system anymore, the import fails.
- country "ch" is not accepted. must be "CH".
- can we set the currency somehow? I had "Fr." but it had been forcefully adopted into EUR. We still don't want that. ;-)
- please advise that install dir be $HOME, because I think ROOT-DIR is sometimes meant as DOCUMENT_ROOT
- also, "public" dir is mandatory, I think for some time (or even up to now) Plesk systems used "httpdocs" as default

is it correct that expenses are not implemented yet? do you plan those?

Gute Grüsse!
manu

**Comment by kevinpapst** [comment]
Thanks for the feedback 👍 Some important improvements were mentioned.

The currency is defined through the customers. So you need to edit each customer and set their currency to `CHF`. I'll see if another importer flag can be added to do that automatically.

Do you want to say, that the docu should be improved with your two `ch` vs `CH` and `$HOME` vs `ROOT_DIR` comments?
 
I don't understand your Plesk comment. I don't think that Plesk needs a directory called httpdocs, but if so: create a symlink to public. But IMO you can configure the document root for every subdomain to a directory of your choice.

**TODO**
- [ ] Create missing users on the fly (like its already done with customers)
- [ ] Add flag for customer currency
- [ ] Update importer docu that country needs to be a uppercase-two character code
- [ ] Check installation docu about $HOME vs  ROOT-DIR vs DOCUMENT_ROOT

**Comment by labor4** [comment]
hi Kevin
HOME: yes docs, just mention it
Countrycode: strtoupper?
Plesk: I meant defaults, but one can change that yes. I was not used to store stuff sub-docroot so it took a bit of adapting

cheers m

**Comment by kevinpapst** [comment]
Not sure if you already handled the import by adjusting the data in your database.
If not, there is a branch in PR #569 which fixes your requests (create unknown user during import).

**Comment by kevinpapst** [comment]
Now available in master
